<a href="https://colab.research.google.com/github/baamsoo/colab_copy/blob/main/230620_numpy_01_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 기초

In [ ]:
# pip install numpy
import numpy as np

In [ ]:
#@title 1차원 배열
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
np.array(range(3))

array([0, 1, 2])

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
#@title 벡터화 연산
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
a % 7

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2])

In [ ]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
(a > 5) & (a < 7)

array([False, False, False, False, False, False,  True, False, False,
       False])

In [ ]:
#@title 2차원 배열
arr = np.array([[0, 1, 2], [3, 4, 5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = np.arange(6).reshape(2, -1)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr, arr.ndim, arr.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [ ]:
#@title 3차원배열
t = np.arange(24).reshape(2, 3, -1)
t, t.ndim, t.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 3,
 (2, 3, 4))

In [ ]:
#@title 배열 복사
v = t.view()
c = t.copy()
t[0][0] = 100
t, v, c

(array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]),
 array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [ ]:
#@title 배열의 인덱싱
# 일차원 배열 = 리스트의 인덱싱
a = np.arange(5)
print(a)
a[0], a[-1]

[0 1 2 3 4]


(0, 4)

In [ ]:
# 다차원 배열 -> [] -> ,를 통해서 축을 구분
b = np.arange(6).reshape(2, -1)
b, b.ndim, b.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [ ]:
b[0, 0]

0

In [ ]:
b[0, 0] = 200
b

array([[200,   1,   2],
       [  3,   4,   5]])

In [ ]:
#@title 배열 슬라이싱
# 다차원 배열 슬라이싱 -> 파이썬 슬라이싱 + 축(axis) ,를 같이 쓰면 된다
a = np.arange(8).reshape(2, -1)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[0], a[0, :]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [ ]:
a[:, 1]

array([1, 5])

In [ ]:
a[1, 1:]

array([5, 6, 7])

In [ ]:
a[1:3, 0:2]

array([[4, 5]])

In [ ]:
#@title 배열 인덱싱 (불리언 배열, 정수 배열)
# 불리언 배열
a1 = np.arange(1, 10, 2)
a2 = np.arange(1, 10)
a1, a2[a2 % 2 != 0], a2[::2]

(array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]))

In [ ]:
# 정수 배열
idx = np.arange(0, 9, 3)
idx, a2[idx]

(array([0, 3, 6]), array([1, 4, 7]))

In [ ]:
import random

r = random.choices(range(len(a2)), k=20)
r, a2[r]

([8, 8, 3, 0, 4, 0, 3, 0, 6, 6, 3, 3, 7, 4, 5, 7, 8, 8, 2, 7],
 array([9, 9, 4, 1, 5, 1, 4, 1, 7, 7, 4, 4, 8, 5, 6, 8, 9, 9, 3, 8]))

In [ ]:
#@title 다차원 배열에서의 배열 인덱싱
a = np.arange(1, 13).reshape(3, -1)
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 2,
 (3, 4))

In [ ]:
a[:, [0, 3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
a[:, [3, 0]]

array([[ 4,  1],
       [ 8,  5],
       [12,  9]])

In [ ]:
a[::-1, [3, 0]]

array([[12,  9],
       [ 8,  5],
       [ 4,  1]])

In [ ]:
a[:, [True, True, False, False]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
np.where(a % 2 == 0)  # 다차원 배열 -> 행별로 인덱스

(array([0, 0, 1, 1, 2, 2]), array([1, 3, 1, 3, 1, 3]))

In [ ]:
arr = np.arange(1, 9)
np.where(arr % 2 == 0)

(array([1, 3, 5, 7]),)

# 배열의 생성과 변형

In [ ]:
x = np.arange(1, 4)
x, x.ndim, x.shape, x.dtype

(array([1, 2, 3]), 1, (3,), dtype('int64'))

In [ ]:
x = np.arange(1.0, 4.0)
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.]), 1, (3,), dtype('float64'))

In [ ]:
x = np.arange(1.0, 4)
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.]), 1, (3,), dtype('float64'))

* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://sharegpt.com/c/YeSV33B

In [ ]:
x = np.arange(1, 4, dtype='f')
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.], dtype=float32), 1, (3,), dtype('float32'))

In [ ]:
np.inf  # 1/0 같은 무한대가 나오는 상황... (에러 안 나고...)

inf

In [ ]:
np.nan  # 0/0 나누던가, nan(null)이 낀 연산 -> 값이 나올 수 없는 연산

nan

In [ ]:
#@title 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
x = np.zeros((3, 5, 1))
x

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [ ]:
np.zeros_like(x)

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 2, 5))  # 모양 -> 리스트, 튜플.

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.ones_like(x)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [ ]:
np.empty(5)  # 값이 뭐가 나올지 몰라...

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(1, 10, 5) # 선형적으로 균등분배된 구간 (선형구간)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.logspace(0.1, 10, 5)

array([1.25892541e+00, 3.75837404e+02, 1.12201845e+05, 3.34965439e+07,
       1.00000000e+10])

In [ ]:
A = np.arange(1, 7).reshape(2, -1)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
A.reshape(-1)  # -1 => 전체 길이

array([1, 2, 3, 4, 5, 6])

In [ ]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]))

In [ ]:
x = np.arange(5)
x, x.shape

(array([0, 1, 2, 3, 4]), (5,))

In [ ]:
x[:, np.newaxis], x[:, np.newaxis].shape

(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 (5, 1))

In [ ]:
x[np.newaxis, :], x[np.newaxis, :].shape

(array([[0, 1, 2, 3, 4]]), (1, 5))

In [ ]:
#@title 배열 연결
a = np.arange(1, 4)
b = np.arange(10, 13)
a, b

(array([1, 2, 3]), array([10, 11, 12]))

In [ ]:
np.concatenate((a, b)) # axis=0

array([ 1,  2,  3, 10, 11, 12])

In [ ]:
np.concatenate((a, b), axis=0)
# np.concatenate((a, b), axis=1) <- 1차원

array([ 1,  2,  3, 10, 11, 12])

In [ ]:
# hstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.hstack((a, b)), np.hstack((a, b)).shape, np.concatenate((a, b), axis=1)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]]),
 (2, 6),
 array([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]]))

In [ ]:
# vstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.vstack((a, b)), np.vstack((a, b)).shape, np.concatenate((a, b), axis=0)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 (4, 3),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [ ]:
# dstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.dstack((a, b)), np.dstack((a, b)).shape

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[[1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.]]]),
 (2, 3, 2))

In [ ]:
# stack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.stack((a, b)), np.stack((a, b)).shape  # axis=0

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [ ]:
axis = 0
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=0

(array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [ ]:
axis = 1
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=1

(array([[[1., 1., 1.],
         [0., 0., 0.]],
 
        [[1., 1., 1.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [ ]:
axis = 2
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=2

(array([[[1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.]]]),
 (2, 3, 2))

In [ ]:
a = np.arange(1, 4)
b = np.arange(4, 7)
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.tile(a, 2)

array([1, 2, 3, 1, 2, 3])

In [ ]:
np.tile(a, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [ ]:
c = np.tile(a, (2, 2))
np.array_split(c, 2)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [ ]:
np.split(c, 2)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [ ]:
np.array_split(c, 2, axis=0)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [ ]:
np.array_split(c, 2, axis=1)

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[1, 2, 3],
        [1, 2, 3]])]